name: Publish NPM

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # required to use OIDC

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "20"
          cache: "pnpm"

      - name: Install Packages.
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: publish
        run: npm publish
