name: Publish NPM

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # required to use OIDC

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Packages.
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: publish
        run: pnpm publish
